### ISSUE TITLE
Port to climacell?

### ISSUE THREAD

**Issue by zensphinx** [vlaine/Weather-Forecast-Dashboard#5]
Hi,

This is excellent work-many thanks! I am using it on my Raspi every day-works perfectly.

Seeing that the darksky API will shut down [at the end of 2021](https://blog.darksky.net/dark-sky-has-a-new-home/) is there any chance that you could consider porting this dashboard to [climacell?](https://developer.climacell.co/)

Many thanks for your work!

Best wishes!

**Comment by vlaine** [comment]
Omg I love your suggestion.  I tried a few api’s but I was never happy with the information provided.  I just checked Climacell and it looks to be as good as DarkSky.  Thank you so much and yes I will work on it promptly.

**Comment by zensphinx** [comment]
Thank you so much! I am looking forward to that. Very best wishes!

**Comment by RobbieIoT** [comment]
Hi,

Here another enthousiast!
Did you also check the OpenWeatherAPI.

Clinacell is pretty expensive, if you want a business plan only for a forecast...

OpenWeather costs $40/month against $144/month on Climacell, which is about the same price as DarkSky..

Just my 2 cents.

**Comment by RobbieIoT** [comment]
> Hi,
> 
> Here another enthousiast!
> Did you also check the OpenWeatherAPI.
> 
> Clinacell is pretty expensive, if you want a business plan only for a forecast...
> 
> OpenWeather costs $40/month against $144/month on Climacell, which is about the same price as DarkSky..
> 
> Just my 2 cents.

Small update: OpenWeather has a port support page: https://openweathermap.org/darksky-openweather

**Comment by karba78** [comment]
> > Hi,
> > Here another enthousiast!
> > Did you also check the OpenWeatherAPI.
> > Clinacell is pretty expensive, if you want a business plan only for a forecast...
> > OpenWeather costs $40/month against $144/month on Climacell, which is about the same price as DarkSky..
> > Just my 2 cents.
> 
> Small update: OpenWeather has a port support page: https://openweathermap.org/darksky-openweather

Hello, did you port it, if yes can you share your config.js (wo the API of course) thks

**Comment by RobbieIoT** [comment]
> > > Hi,
> > > Here another enthousiast!
> > > Did you also check the OpenWeatherAPI.
> > > Clinacell is pretty expensive, if you want a business plan only for a forecast...
> > > OpenWeather costs $40/month against $144/month on Climacell, which is about the same price as DarkSky..
> > > Just my 2 cents.
> > 
> > 
> > Small update: OpenWeather has a port support page: https://openweathermap.org/darksky-openweather
> 
> Hello, did you port it, if yes can you share your config.js (wo the API of course) thks

Hi,

I had one try some time ago, but haven't got it working yet.
The issue is that there are too many variables to migrate quickly and missing one already causes a blank screen.

I did implemented it in a special way to a project (narrow casting) of mine:

![image](https://user-images.githubusercontent.com/36163166/112458816-8226fc00-8d5d-11eb-96d5-6c3e048f9f44.png)

The forecast is a chrome 'screenshot' from a stripped down layout with a fixed resolution, which is made every new hour.
Updated many things to make it a fit inside this test setup, but it's running fine.

The date/time is a separate TKinter drawing which updates every minute, but it can also be used to present custom text.

There's time until the end of the year, so my first priority is to build a stable example...

In between I will take another shot in the migration...

**Comment by vlaine** [comment]
I did not forget you.  I kept the DarkSky code in case some of you are still using it.  I ported the code to OpenWeatherMap and will do the same for Climacell soon. 
NEW: you can now configure almost everything directly from the url.  No need to manipulate the config file.

**Comment by vlaine** [comment]
I like what you have done with it.  
The new version is easier to configure if you do it directly from the url using querystring parameters.  I hope it will help you.

ex: http://{yourdomain}/index.html?apikey=00000000000000000000000000000000&latitude=45.4973&longitude=-73.5707&lang=en&theme=black

> 
> 
> > > > Hi,
> > > > Here another enthousiast!
> > > > Did you also check the OpenWeatherAPI.
> > > > Clinacell is pretty expensive, if you want a business plan only for a forecast...
> > > > OpenWeather costs $40/month against $144/month on Climacell, which is about the same price as DarkSky..
> > > > Just my 2 cents.
> > > 
> > > 
> > > Small update: OpenWeather has a port support page: https://openweathermap.org/darksky-openweather
> > 
> > 
> > Hello, did you port it, if yes can you share your config.js (wo the API of course) thks
> 
> Hi,
> 
> I had one try some time ago, but haven't got it working yet.
> The issue is that there are too many variables to migrate quickly and missing one already causes a blank screen.
> 
> I did implemented it in a special way to a project (narrow casting) of mine:
> 
> ![image](https://user-images.githubusercontent.com/36163166/112458816-8226fc00-8d5d-11eb-96d5-6c3e048f9f44.png)
> 
> The forecast is a chrome 'screenshot' from a stripped down layout with a fixed resolution, which is made every new hour.
> Updated many things to make it a fit inside this test setup, but it's running fine.
> 
> The date/time is a separate TKinter drawing which updates every minute, but it can also be used to present custom text.
> 
> There's time until the end of the year, so my first priority is to build a stable example...
> 
> In between I will take another shot in the migration...

**Comment by RobbieIoT** [comment]
> I like what you have done with it.
> The new version is easier to configure if you do it directly from the url using querystring parameters. I hope it will help you.
> 
> ex: http://{yourdomain}/index.html?apikey=00000000000000000000000000000000&latitude=45.4973&longitude=-73.5707&lang=en&theme=black
> 
> > > > > Hi,
> > > > > Here another enthousiast!
> > > > > Did you also check the OpenWeatherAPI.
> > > > > Clinacell is pretty expensive, if you want a business plan only for a forecast...
> > > > > OpenWeather costs $40/month against $144/month on Climacell, which is about the same price as DarkSky..
> > > > > Just my 2 cents.
> > > > 
> > > > 
> > > > Small update: OpenWeather has a port support page: https://openweathermap.org/darksky-openweather
> > > 
> > > 
> > > Hello, did you port it, if yes can you share your config.js (wo the API of course) thks
> > 
> > 
> > Hi,
> > I had one try some time ago, but haven't got it working yet.
> > The issue is that there are too many variables to migrate quickly and missing one already causes a blank screen.
> > I did implemented it in a special way to a project (narrow casting) of mine:
> > ![image](https://user-images.githubusercontent.com/36163166/112458816-8226fc00-8d5d-11eb-96d5-6c3e048f9f44.png)
> > The forecast is a chrome 'screenshot' from a stripped down layout with a fixed resolution, which is made every new hour.
> > Updated many things to make it a fit inside this test setup, but it's running fine.
> > The date/time is a separate TKinter drawing which updates every minute, but it can also be used to present custom text.
> > There's time until the end of the year, so my first priority is to build a stable example...
> > In between I will take another shot in the migration...

Hi @vlaine ,

Thank you so much for the port, I will check where I went wrong !!

**Comment by vlaine** [comment]
> > I like what you have done with it.
> > The new version is easier to configure if you do it directly from the url using querystring parameters. I hope it will help you.
> > ex: http://{yourdomain}/index.html?apikey=00000000000000000000000000000000&latitude=45.4973&longitude=-73.5707&lang=en&theme=black
> > > > > > Hi,
> > > > > > Here another enthousiast!
> > > > > > Did you also check the OpenWeatherAPI.
> > > > > > Clinacell is pretty expensive, if you want a business plan only for a forecast...
> > > > > > OpenWeather costs $40/month against $144/month on Climacell, which is about the same price as DarkSky..
> > > > > > Just my 2 cents.
> > > > > 
> > > > > 
> > > > > Small update: OpenWeather has a port support page: https://openweathermap.org/darksky-openweather
> > > > 
> > > > 
> > > > Hello, did you port it, if yes can you share your config.js (wo the API of course) thks
> > > 
> > > 
> > > Hi,
> > > I had one try some time ago, but haven't got it working yet.
> > > The issue is that there are too many variables to migrate quickly and missing one already causes a blank screen.
> > > I did implemented it in a special way to a project (narrow casting) of mine:
> > > ![image](https://user-images.githubusercontent.com/36163166/112458816-8226fc00-8d5d-11eb-96d5-6c3e048f9f44.png)
> > > The forecast is a chrome 'screenshot' from a stripped down layout with a fixed resolution, which is made every new hour.
> > > Updated many things to make it a fit inside this test setup, but it's running fine.
> > > The date/time is a separate TKinter drawing which updates every minute, but it can also be used to present custom text.
> > > There's time until the end of the year, so my first priority is to build a stable example...
> > > In between I will take another shot in the migration...
> 
> Hi @vlaine ,
> 
> Thank you so much for the port, I will check where I went wrong !!

If you are stuck, let me know so I can help.

**Comment by RobbieIoT** [comment]
Hi Vlaine,

It's been a while ago!
Also, the project I worked on that period was paused (still is), but due to
my registration at DarkSky, I received an email from AppleInc regarding the
DarkSky API:

*Introducing WeatherKit*

*Hello there,*
*We wanted to let you know about a change coming to Dark Sky. Beginning on
March 31st, 2023 the Dark Sky API will no longer be available. To prepare,
we encourage you to learn more about WeatherKit, a new Apple API available
on iOS, iPadOS, macOS, tvOS, and web that provides access to the new Apple
Weather forecast data.*
*You can learn more here.*

*As always, we appreciate your support, and will continue to update you
with any future changes.*

*Thanks,*
*The Dark Sky Team*


They created something new, called WeatherKit:
https://developer.apple.com/weatherkit/

So I thought to share it with you!


Met vriendelijke groet / with kind regards,

Robert Bos
Technisch specialist

<http://www.elseco.nl>

*Uw partner voor o.a.:*
*Camerasystemen - Lifttelefoons - Videofoonsystemen - Dataverbindingen  -
Narrowcasting - Sensorlijsten - Liftmonitoring*

ELSECO B.V.
IJsselmeerweg 1
1411 AA  NAARDEN

Mobiel:       +31 6 52 786 149
Direct:        +31 35 69 55 106
Algemeen: +31 35 69 55 100

Email: ***@***.*** ***@***.***>*
Web:   www.elseco.nl

<https://www.facebook.com/ElsecoBv/>
<https://www.linkedin.com/company/elseco-bv>


<https://www.linkedin.com/company/elseco-bv>



Op ma 29 mrt. 2021 om 13:06 schreef vlaine ***@***.***>:
